login: &login
  adapter: mysql2
  username: root
  password:
  host: localhost

development:
  <<: *login
  database: statusus_dev

test:
  <<: *login
  database: statusus_test

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
