login: &login
  adapter: mysql2
  username: root
  password:
  host: localhost

development:
  <<: *login
  database: statusus_dev

test:
  <<: *login
  database: statusus_test

production:
  adapter: mysql2
  encoding: utf8
  database: statusus_production
  username: statusus
  password: 5tatu5u5
  host: localhost
  port: 3306
