login: &login
  adapter: mysql2
  database: statusus_development
  username: root
  password:
  host: localhost

development:
  <<: *login

production:
  <<: *login

test:
  <<: *login
  database: statusus_test
